### PR TITLE
updated puppet-redirect url attribute

### PR DESCRIPTION
**Pull request by PatrykSzwer**
Related to https://github.com/Palindrom/palindrom-redirect/issues/1

### CODE REVIEW

**Comment by Mihaiii** [comment]
To be honest, this would be a good moment to change `puppet-redirect` to `palindrom-reddirect`, but the latest RC doesn't have `palindrom-reddirect` so everything is ok.

**Comment by Mihaiii** [comment]
Please don't merge this one yet.

**Comment by PatrykSzwer** [comment]
I've replaced puppet-redirect with palindrom-redirect but I'm getting some strange warning in console:
`palindrom-dom.min.js:2 `puppet-redirect-pushstate` event is deprecated, please use `palindrom-redirect-pushstate`, if you're using `puppet-redirect`, please upgrade to `palindrom-redirect`
Please check if you have same. Do You have any idea what is causing it and how it should be fixed?

**Comment by Mihaiii** [comment]
I get the same when I sign out, but that might be related with SingIn app.

**Comment by Mihaiii** [comment]
Also, checks are failing.

**Comment by PatrykSzwer** [comment]
Those failing checks are not related to this issue. It's going to be fixed with this PR: https://github.com/Starcounter/Website/pull/248
Since everything else is ok, I'll merge this.

**Pull request merged**
